apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-app-deployment
  namespace: blue  # Specify the namespace (blue or green)
  labels:
    app: crypto-app
spec:
  replicas: 3  # Number of app instances (3 replicas)
  selector:
    matchLabels:
      app: crypto-app
  template:
    metadata:
      labels:
        app: crypto-app
    spec:
      containers:
        - name: crypto-app
          image: 654654534276.dkr.ecr.eu-north-1.amazonaws.com/crypto-price:latest  # ECR image
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: crypto-app-service
  namespace: blue  # Specify the namespace (blue or green)
spec:
  type: LoadBalancer  # Accessible from outside the cluster
  selector:
    app: crypto-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
