apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-app-deployment-blue
  labels:
    app: crypto-app-blue
spec:
  replicas: 2  # Number of app instances (replicas)
  selector:
    matchLabels:
      app: crypto-app-blue
  template:
    metadata:
      labels:
        app: crypto-app-blue
    spec:
      containers:
        - name: crypto-app
          image: 654654534276.dkr.ecr.eu-north-1.amazonaws.com/crypto-price:latest  # Updated with our ECR image
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: crypto-app-service-blue
spec:
  type: LoadBalancer  # This makes our app accessible from outside the cluster
  selector:
    app: crypto-app-blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
