apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-app-deployment-green
  namespace: green  # Specifies the namespace for green environment
  labels:
    app: crypto-app-green
spec:
  replicas: 2  # Number of app instances (replicas)
  selector:
    matchLabels:
      app: crypto-app-green
  template:
    metadata:
      labels:
        app: crypto-app-green
    spec:
      containers:
        - name: crypto-app
          image: 654654534276.dkr.ecr.eu-north-1.amazonaws.com/crypto-price:latest  # ECR image for the app
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: crypto-app-service-green
  namespace: green  # Specifies the namespace for green environment
spec:
  type: LoadBalancer  # This makes the app accessible from outside the cluster
  selector:
    app: crypto-app-green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
