name: EKS Blue-Green Deployment

on:
  push:
    branches:
      - master  # Triggers deployment on push to the master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Secrets stored in GitHub
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1  # Region where our EKS and ECR resources are located

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push the Docker image to ECR
        run: |
          docker build -t crypto-price:latest .  # Build the Docker image
          docker tag crypto-price:latest 654654534276.dkr.ecr.eu-north-1.amazonaws.com/crypto-price:latest
          docker push 654654534276.dkr.ecr.eu-north-1.amazonaws.com/crypto-price:latest

      - name: Update the Blue environment
        run: |
          kubectl apply -f k8s/deployments/deployment-blue.yaml  # Apply the blue environment deployment
          kubectl rollout status deployment/crypto-app-deployment-blue -n blue  # Wait for the blue deployment to complete

      - name: Update the Green environment
        run: |
          kubectl apply -f k8s/deployments/deployment-green.yaml   # Apply the green environment deployment
          kubectl rollout status deployment/crypto-app-deployment-green -n green  # Wait for the green deployment to complete

      - name: Verify Deployment
        run: |
          kubectl get pods -n blue  # List pods in the blue namespace
          kubectl get pods -n green  # List pods in the green namespace
          kubectl get services -n blue  # List services in the blue namespace
          kubectl get services -n green  # List services in the green namespace
